name: 'C++ Style Check'
description: 'Runs C++ style check with Uncrustify'
author: 'coleaeason'
inputs:
  configPath:
    description: 'Alternate configuration file to use'
    required: false
  fileMask:
    description: 'Which files to check'
    required: false
    default: '*.cpp *.h *.hpp *.cxx'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
    icon: 'edit-3'
    color: 'green'
